Move-Item "dsp_engine.py" -Destination "core\" -Force
Move-Item "constants.py" -Destination "core\" -Force
Move-Item "config.json" -Destination "core\" -Force
Move-Item "charts.py" -Destination "ui\" -Force
Move-Item "tabs" -Destination "ui\" -Force
Move-Item "components" -Destination "ui\" -Force
Move-Item "make_word.py" -Destination "scripts\" -Force
Move-Item "create_dummy_iq.py" -Destination "scripts\" -Force
Move-Item "test_file.py" -Destination "scripts\" -Force
Move-Item "*.docx" -Destination "docs\" -Force
Move-Item "*.txt" -Destination "docs\" -Force
Move-Item "*.iq" -Destination "data\" -Force
